POST http://localhost:8090/register
Content-Type: application/json

{
  "first_name": "Noah",
  "last_name": "Florin",
  "password": "$eCuR1tY15Re4l"
}

###

POST http://localhost:8090/login
Content-Type: application/json

{
  "first_name": "Noah",
  "last_name": "Florin",
  "password": "$eCuR1tY15Re4l"
}
